version: "3.9"

services:

 backend:
  build: ./bckend
  container_name: django_backend
  ports:
    "8000:8000"
  volumes:
    ./backend:/app
  enviroment:
    DJANGO_ALLOWED_HOSTS+*
    DJANGO_DEBUG=True
  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      "3000:3000"
    volumes:
      ./frontend:/app
    stind_open: true 
    envirument:
      CHOKIDAR_USEPOLING=true